// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9D-efQ9e2_AuYlWXGpvDf5UX8JGoFeFY',
    appId: '1:953556829974:web:0c5b7d178354a1cee6f237',
    messagingSenderId: '953556829974',
    projectId: 'ecommerce2-c470a',
    authDomain: 'ecommerce2-c470a.firebaseapp.com',
    storageBucket: 'ecommerce2-c470a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrwGQNCT8dQQ1VQE_Y_4gB0eyxGD5mpvQ',
    appId: '1:953556829974:android:e72f9eb4eece8377e6f237',
    messagingSenderId: '953556829974',
    projectId: 'ecommerce2-c470a',
    storageBucket: 'ecommerce2-c470a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPhDOwkMmu0xEWhzk2Tat3SENCOD9UvIw',
    appId: '1:953556829974:ios:bc97af551ddc5de5e6f237',
    messagingSenderId: '953556829974',
    projectId: 'ecommerce2-c470a',
    storageBucket: 'ecommerce2-c470a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
